export const categoryTree = [
  {
    id: 'electronics',
    name: '电子产品',
    subcategories: ['手机平板', '电脑', '家电', '智能穿戴', '数码配件'],
  },
  {
    id: 'fresh-food',
    name: '食品生鲜',
    subcategories: ['生鲜果蔬', '鲜肉水产', '零食速食', '粮油调味', '乳品烘焙'],
  },
  {
    id: 'drinks',
    name: '酒水饮料',
    subcategories: ['饮料冲调', '啤酒洋酒', '白酒红酒', '茶饮咖啡'],
  },
  {
    id: 'home-living',
    name: '家居百货',
    subcategories: ['厨房用品', '收纳清洁', '纸品湿巾', '床品家纺'],
  },
  {
    id: 'beauty-care',
    name: '个护美妆',
    subcategories: ['洗护清洁', '护肤彩妆', '口腔护理', '身体护理'],
  },
  {
    id: 'mother-baby',
    name: '母婴玩具',
    subcategories: ['奶粉辅食', '尿裤湿巾', '玩具乐器', '童装童鞋'],
  },
  {
    id: 'fashion',
    name: '服饰鞋包',
    subcategories: ['男装', '女装', '运动鞋服', '箱包配饰'],
  },
]

export const catalogProducts = [
  {
    id: 2001,
    name: '旗舰折叠屏手机',
    desc: '高刷大屏与轻薄机身兼顾，热门旗舰限时直降。',
    price: 6999,
    sales: 2680,
    popularity: 96,
    unit: '/台',
    theme: 'electronics-phone',
    category: '电子产品',
    subcategory: '手机平板',
    featured: true,
    badges: ['12期免息', '新品热卖'],
  },
  {
    id: 2002,
    name: '轻薄办公笔记本',
    desc: '14 英寸高色域屏，适合学习办公和移动创作。',
    price: 5299,
    sales: 1920,
    popularity: 91,
    unit: '/台',
    theme: 'electronics-laptop',
    category: '电子产品',
    subcategory: '电脑',
    featured: true,
    badges: ['办公爆款'],
  },
  {
    id: 2003,
    name: '空气炸锅 5L',
    desc: '少油快烤，家常炸物和烘焙都很省心。',
    price: 299,
    sales: 3560,
    popularity: 88,
    unit: '/台',
    theme: 'electronics-appliance',
    category: '电子产品',
    subcategory: '家电',
    featured: false,
    badges: ['厨房优选'],
  },
  {
    id: 2004,
    name: '智能运动手表',
    desc: '全天心率监测，跑步骑行记录更完整。',
    price: 899,
    sales: 1480,
    popularity: 84,
    unit: '/只',
    theme: 'electronics-watch',
    category: '电子产品',
    subcategory: '智能穿戴',
    featured: false,
    badges: ['穿戴新品'],
  },
  {
    id: 2005,
    name: '草莓鲜果礼盒',
    desc: '果香浓郁，冷链到家，适合全家分享。',
    price: 49.9,
    sales: 4250,
    popularity: 93,
    unit: '/盒',
    theme: 'fresh-fruit',
    category: '食品生鲜',
    subcategory: '生鲜果蔬',
    featured: true,
    badges: ['当季鲜果'],
  },
  {
    id: 2006,
    name: '鲜活大虾套餐',
    desc: '鲜活直送，家庭聚餐更省心。',
    price: 88,
    sales: 2380,
    popularity: 90,
    unit: '/份',
    theme: 'fresh-seafood',
    category: '食品生鲜',
    subcategory: '鲜肉水产',
    featured: true,
    badges: ['冷链锁鲜'],
  },
  {
    id: 2007,
    name: '谷物早餐脆',
    desc: '香脆轻食，适合早餐和下午茶加餐。',
    price: 19.9,
    sales: 5120,
    popularity: 87,
    unit: '/袋',
    theme: 'fresh-snack',
    category: '食品生鲜',
    subcategory: '零食速食',
    featured: false,
    badges: ['休闲零食'],
  },
  {
    id: 2008,
    name: '原香有机牛奶',
    desc: '口感醇厚，早餐囤货常备。',
    price: 59.9,
    sales: 2860,
    popularity: 82,
    unit: '/箱',
    theme: 'fresh-dairy',
    category: '食品生鲜',
    subcategory: '乳品烘焙',
    featured: false,
    badges: ['早餐囤货'],
  },
  {
    id: 2009,
    name: '冷泡茉莉茶',
    desc: '清爽回甘，冰镇饮用更适合夏日。',
    price: 15.9,
    sales: 4680,
    popularity: 95,
    unit: '/瓶',
    theme: 'drink-tea',
    category: '酒水饮料',
    subcategory: '饮料冲调',
    featured: true,
    badges: ['解暑热卖'],
  },
  {
    id: 2010,
    name: '精品手冲咖啡豆',
    desc: '花果香调，适合手冲和意式拼配。',
    price: 69.9,
    sales: 1760,
    popularity: 85,
    unit: '/袋',
    theme: 'drink-coffee',
    category: '酒水饮料',
    subcategory: '茶饮咖啡',
    featured: false,
    badges: ['咖啡馆同款'],
  },
  {
    id: 2011,
    name: '厨房纸巾加厚装',
    desc: '吸水吸油一步到位，居家高频消耗品。',
    price: 24.9,
    sales: 6020,
    popularity: 92,
    unit: '/提',
    theme: 'home-paper',
    category: '家居百货',
    subcategory: '纸品湿巾',
    featured: true,
    badges: ['满减好物'],
  },
  {
    id: 2012,
    name: '可折叠收纳箱',
    desc: '衣物玩具都能收，搬家整理更轻松。',
    price: 39.9,
    sales: 2140,
    popularity: 81,
    unit: '/个',
    theme: 'home-storage',
    category: '家居百货',
    subcategory: '收纳清洁',
    featured: false,
    badges: ['家务省心'],
  },
  {
    id: 2013,
    name: '氨基酸洁面乳',
    desc: '温和清洁不紧绷，日常通勤党友好。',
    price: 79,
    sales: 1660,
    popularity: 86,
    unit: '/支',
    theme: 'beauty-cleanser',
    category: '个护美妆',
    subcategory: '护肤彩妆',
    featured: false,
    badges: ['口碑回购'],
  },
  {
    id: 2014,
    name: '电动牙刷套装',
    desc: '多档清洁模式，晨晚护理更细致。',
    price: 219,
    sales: 1880,
    popularity: 83,
    unit: '/套',
    theme: 'beauty-toothbrush',
    category: '个护美妆',
    subcategory: '口腔护理',
    featured: false,
    badges: ['个护精选'],
  },
  {
    id: 2015,
    name: '婴幼儿营养米粉',
    desc: '细腻易冲泡，辅食阶段更安心。',
    price: 58,
    sales: 1720,
    popularity: 80,
    unit: '/罐',
    theme: 'baby-cereal',
    category: '母婴玩具',
    subcategory: '奶粉辅食',
    featured: false,
    badges: ['母婴常备'],
  },
  {
    id: 2016,
    name: '积木启蒙礼盒',
    desc: '色彩明快，锻炼专注力和动手能力。',
    price: 129,
    sales: 1940,
    popularity: 84,
    unit: '/盒',
    theme: 'baby-toy',
    category: '母婴玩具',
    subcategory: '玩具乐器',
    featured: false,
    badges: ['儿童热卖'],
  },
  {
    id: 2017,
    name: '轻弹运动跑鞋',
    desc: '包裹支撑到位，通勤慢跑都合适。',
    price: 269,
    sales: 2580,
    popularity: 89,
    unit: '/双',
    theme: 'fashion-shoe',
    category: '服饰鞋包',
    subcategory: '运动鞋服',
    featured: true,
    badges: ['换季上新'],
  },
  {
    id: 2018,
    name: '通勤双肩电脑包',
    desc: '分仓收纳设计，日常出差都能装。',
    price: 159,
    sales: 1430,
    popularity: 79,
    unit: '/个',
    theme: 'fashion-bag',
    category: '服饰鞋包',
    subcategory: '箱包配饰',
    featured: false,
    badges: ['出行推荐'],
  },
]

export function getCategoryByName(categoryName) {
  return categoryTree.find((item) => item.name === categoryName) || categoryTree[0]
}

export function getSubcategories(categoryName) {
  return getCategoryByName(categoryName).subcategories
}

export function getFeaturedProducts(categoryName) {
  const featured = catalogProducts.filter((item) => item.featured && (!categoryName || item.category === categoryName))
  if (featured.length) {
    return featured
  }

  return catalogProducts.filter((item) => !categoryName || item.category === categoryName).slice(0, 4)
}
